[tool.poetry]
name = "benzinpreis-app"
version = "0.1.0"
description = "Bensinpreis App"
authors = ["Donald Kapyouo <dkapyouo@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
